apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dvt-report-generator
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/hardware-firmware-dvt/dvt-report-generator
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp
      volumes:
      - name: temp-storage
        emptyDir: {}
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
venv_1/
ENV/
env.bak/
venv.bak/

# IDEs
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Git
.git/
.gitignore

# Logs
*.log

# Local development
.env
.env.local

# Output files (these will be generated in container)
Output/
attachments/

# Documentation
*.md
DVT_Test_Report_Generator_AI_Tasks_1.md
